final class Icons {
    static let plus = "plus"
    static let attach = "attach"
    static let chevronLeft = "chevron_left"
    static let explore = "explore"
    static let exploreFilled = "explore_filled"
    static let feed = "feed"
    static let feedFilled = "feed_filled"
    static let heart = "heart"
    static let heartFilled = "heart_filled"
    static let instagramLogo = "instagram_logo"
    static let lock = "lock"
    static let logo = "logo"
    static let menuCircle = "menu_circle"
    static let menu = "menu"
    static let message = "message"
    static let profile = "profile"
    static let profileFilled = "profile_filled"
    static let repost = "repost"
    static let send = "send"
    static let write = "write"
    static let writeFilled = "write_filled"
}
